# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.

[server]
bootstrap_expect = 3
data_dir = "/hab/svc/nomad/data"


# This is the default config for consul
# It's an all or nothing at the moment...
# [consul]
# address = "127.0.0.1:8500"

# The service name to register the server and client with Consul.
# server_service_name = "nomad"
# client_service_name = "nomad-client"

# Enables automatically registering the services.
# auto_advertise = "true"

# Enabling the server and client to bootstrap using Consul.
# server_auto_join = "true"
# client_auto_join = "true"
