# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.

[server]
bootstrap_expect = 3
data-dir = "/hab/svc/nomad/data
